version: "1.0"
project:
  name: bodywork-test-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1
  usage_stats: false
  run_on_failure: on_fail_stage
stages:
  stage_1:
    executable_module_path: stage_1/main.py
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 60
      retries: 4
    secrets:
      FOO: foobar-secret
      BAR: foobar-secret
    requirements:
      - numpy==1.19.1
  on_fail_stage:
    executable_module_path: on_fail_stage/main.py
    cpu_request: 0.5
    memory_request_mb: 250
    batch:
      max_completion_time_seconds: 60
      retries: 4
logging:
  log_level: INFO
